### ISSUE TITLE
koff etcd is not documented

### ISSUE THREAD

**Issue by palonsoro** [gmeghnag/koff#3]
I cannot find documentation of `koff etcd` subcommand in https://gmeghnag.github.io/koff/ and the help is too short.

Maybe I made some mistake in finding the docs?

Thanks in advance.

**Comment by gmeghnag** [comment]
closed with 8b0acf200a0beef826cb333d6b52d8ab6ae80ed5

**Comment by palonsoro** [comment]
Thx!
